config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  get 'pages/rules'
  get 'pages/rgpd'
  get 'pages/presentation'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :user do
    resources :bookings, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :accepted
        patch :refused
      end
    end
    resources :flats, only: [:index] do
    end
  end

  resources :flats do
    resources :bookings, only: [:new, :create]
    member do
      patch :delete_photos
    end
  end

  resources :client, only: [:new, :create] do
    resources :bookings, only: [:create]
  end

 resources :bookings, only: [:new, :create, :show, :edit, :update]

 resources :contacts, only: [:new, :create]
end

app/models/flat.rb
class Flat < ApplicationRecord
BELONGING = ["Immeuble Comara", "Partenaire"]

  has_one_attached :picture
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :equipment, dependent: :destroy
  accepts_nested_attributes_for :equipment
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :description, :price_per_day, :max_capacity, :min_capacity, :price_xof, presence: true

    def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_flat, only: %i[show edit update destroy delete_photos]

  def index
    start_date, end_date = params[:start_date_response].split(' to ')
    @booked_flat_ids= Booking.where(status: 'confirmed')
      .where('(start_date BETWEEN :start_date AND :end_date) OR (end_date BETWEEN :start_date AND :end_date)', start_date: start_date, end_date: end_date)
      .pluck(:flat_id)

    @flats = Flat.where.not(id: @booked_flat_ids)
      .where('max_capacity >= ? AND min_capacity <= ?', params[:capacity_response], params[:capacity_response])

    @flat_place = Flat.geocoded
    @markers = @flats.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @flat = Flat.new
    build_equipments
  end

  def create
    @flat= Flat.new(flat_params)

    if @flat.belonging == true
      @flat.longitude = -3.9679002709940625
      @flat.latitude = 5.302209635104108
    end


    if @flat.save

      redirect_to user_flats_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    if @flat.save
    redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to user_flats_path
  end

  def delete_photos
    @flat.photos.purge
    flash[:delete_photos] = "Les photos sont supprimées."
  end

  private

  def flat_params
    params.require(:flat).permit(
      :name,
      :description,
      :price_per_day,
      :price_xof,
      :address,
      :picture,
      :longitude,
      :latitude,
      :max_capacity,
      :min_capacity,
      :belonging,
      :offer,
      photos: [],
      equipment_attributes: [:id, :name, :available, :pricing, :icon])
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def build_equipments
    # Equipment::NAMES.each do |name|
    #   @flat.equipment.new(name: name)
    # end
    @flat.equipment.new(name: 'kitchen', icon: 'fal fa-hat-chef')
    @flat.equipment.new(name: 'air conditioner', icon: 'fal fa-air-conditioner')
    @flat.equipment.new(name: 'hangers', icon: 'fal fa-tshirt')
    @flat.equipment.new(name: 'washing machine', icon: 'fal fa-washer')
    @flat.equipment.new(name: 'television', icon: 'fal fa-tv')
    @flat.equipment.new(name: 'private entrance', icon: 'fal fa-key')
    @flat.equipment.new(name: 'sheets', icon: 'fal fa-blanket')
    @flat.equipment.new(name: 'work space', icon: 'fal fa-laptop-code')
    @flat.equipment.new(name: 'fridge', icon: 'fal fa-refrigerator')
    @flat.equipment.new(name: 'dishes', icon: 'fal fa-glass')
    @flat.equipment.new(name: 'utensil', icon: 'fal fa-utensils')
    @flat.equipment.new(name: 'cooker', icon: 'fal fa-oven')
    @flat.equipment.new(name: 'balcony', icon: 'fal fa-sun')
    @flat.equipment.new(name: 'backyard', icon: 'fal fa-sun')
    @flat.equipment.new(name: 'carbon monoxide detector', icon: 'fal fa-sensor')
    @flat.equipment.new(name: 'hot water', icon: 'fal fa-hand-holding-water')
    @flat.equipment.new(name: 'parking', icon: 'fal fa-car')
    @flat.equipment.new(name: 'long stay', icon: 'fal fa-calendar-plus')
    @flat.equipment.new(name: 'tumble dryer', icon: 'fal fa-dryer-alt')
    @flat.equipment.new(name: 'wifi', icon: 'fal fa-wifi')
    @flat.equipment.new(name: 'store', icon: 'fal fa-booth-curtain')
    @flat.equipment.new(name: 'luggage', icon: 'fal fa-suitcase')
  end

end

app/controllers/user/flats_controller.rb
class User::FlatsController < ApplicationController
  def index
    @flats_comara = Flat.where(belonging: true)
    @flats_partners = Flat.where(belonging: false)
  end
end

app/views/flats/_form.html.erb
<%= simple_form_for @booking do |f| %>
          <% if @booking.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @booking.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
            <%= f.input :start_date,
                        as: :string,
                        required: false,
                        label: 'Dates d\'arrivée' %>
            <%= f.input :end_date,
                        as: :string,
                        required: false,
                        label: 'Date de départ' %>

              <div class="d-flex flex-row-reverse mt-4">
                <%= f.submit "Réservez" %>
              </div>
            </div>
        <% end %>

app/views/flats/_photos.html.erb
<div class="photos mx-0 px-0">
  <div class="dotnav-container mx-0 px-0">
    <div class="row">
      <div class="col-11">

      </div>
      <div class="col-1">
       <i class="fas fa-times mt-2 close-photos"></i>
      </div>
    </div>
    <div class="text-center">
      <div class="carroussel">
          <% @flat.photos.each do |photo| %>
            <div class="bla d-flex justify-content-center">
                <%= cl_image_tag photo.key, crop: :thumb, class: "grande-photo" %>
            </div>
          <% end %>
      </div>
      <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
      <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

      <script type="text/javascript">
        $(document).ready(() => {
          $('.carroussel').slick({
              dots: true,
      infinite: true,
      speed: 500,
      fade: true,
      cssEase: 'linear'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<div class="container bg-white my-5">
  <h1 class="p-4">Modifier une annonce</h1>
    <%= simple_form_for @flat do |f| %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <%= f.input :name,
                    as: :string,
                    required: false,
                    label: 'Nom' %>
        <%= f.input :price_per_day,
                    as: :integer,
                    required: false,
                    label: 'Prix par nuit' %>
        <%= f.input :description,
                    as: :text,
                    required: false,
                    label: 'Description' %>
        <%= f.input :offer,
                    as: :text,
                    required: false,
                    label: 'Offre' %>
        <%= f.input :picture,
                    as: :file,
                    label: 'Photo principale' %>
        <%= f.input :photos,
                    as: :file,
                    input_html: { multiple: true },
                    label: 'Photos secondaires' %>
        <%= link_to delete_photos_flat_path(@flat), method: :patch do %>
          <p>Supprimer les photos</p>
        <% end %>
        <div class="row">
          <%= f.simple_fields_for :equipment do |c| %>
            <div class="col-md-6 my-3">
              <div class="row ml-2">
                <div class="col-md-5">
                  <p class="equipment-name"><%= t(c.object.name) %></p>
                </div>
                <%= c.input :name, as: :hidden %>
                <%= c.input :icon, as: :hidden %>
                <div class="col-md-3">
                  <%= c.input :available, as: :boolean, label: 'Disponible' %>
                </div>
                <div class="col-md-4">
                  <%= c.input :pricing, as: :boolean, label: 'Disponible (payant)' %>
                </div>
              </div>
            </div>
          <% end %>
          </div>
          <div class="d-flex justify-content-center">
            <%= f.submit "Modifier", class: 'back-to-home-link my-5' %>
          </div>
        </div>
    <% end %>
</div>

app/views/flats/index.html.erb
<div class="index-flat">
  <div class="container-fluid">
    <div class="row text-right">
    <div class="home-search-bar">
      <%= form_tag flats_path, method: :get do %>
          <div class="search-components">
            <%= text_field_tag :start_date_response,
                  params[:start_date_response],
                  input_html: {class: "datepicker"},
                  class: "datepicker-query bg-white",
                  placeholder: "Date d'arrivée" %>
            <%= text_field_tag :end_date_response,
                  params[:end_date_response],
                  input_html: {class: "end_date"},
                  class: "end-date-query bg-white",
                  placeholder: "Date de départ" %>
            <div class="icon-capacity">
            <div class="user-capacity">
              <i class="fas fa-user-friends"></i>
            </div>
          <%= select_tag :capacity_response,
                options_for_select([ "1", "2", "3", "4", "5", "6" ], params[:capacity_response]),
                class: "capacity-home-booking bg-white" %>
            </div>
          <%= submit_tag 'Recherchez',
          class: "submit-index-show"%>
        </div>
      <% end %>
    </div>
    </div>
    <% if @flats.count != 0 %>
      <div class="row block-result">
        <div class="col-md-8 mb-5">
          <div class="title-page-index-flats mt-2">
            <h1 class="ml-5 mt-5 title-index-flat">Résultats de votre recherche</h1>
          </div>
          <div class="index-flats ml-4">
            <% @flats.each do |flat| %>
              <%= link_to flat_path(flat), class: "link-show-flat" do %>
              <div class="flat-list m-4">
                <div class="d-flex">
                  <div class="col-3 px-0 d-flex align-items-center">
                    <%= cl_image_tag flat.picture.key, crop: :scale, class: "photo-flat-index" %>
                  </div>
                  <div class="col-6">
                    <div class="row">
                      <div class="block-info">
                        <h3 class="pl-2 pt-2" id="flat-name-index"><%= flat.name %></h3>
                      </div>
                    </div>
                    <div class="row">
                      <div class="block-info">
                        <div class="d-flex">
                          <i class="fas fa-user mt-1 mr-2 pl-3 user-solid-index"></i>
                          <p  id="capacity-flat"><%= flat.max_capacity %> personnes</p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="block-info">
                        <div class="price-flat-index d-flex">
                          <p class="price-per-day-index mt-1 mr-2 pl-3" data-price="<%= flat.price_per_day %>" data-flat="<%= flat.id %>"><%= flat.price_xof %> XOF/nuit</p>
                          <p class="price-per-day-xof" data-price="<%= flat.price_xof %>" data-flat="<%= flat.id %>"></p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-3">
                    <div class="row">
                      <div class="block-info">
                      </div>
                    </div>
                    <div class="row">
                      <div class="block-info">
                        <p class="text-center" id="total-price-flat-index"><span class="total-price-xof pr-1"data-price="<%= flat.price_per_day %>" data-flat="<%= flat.id %>"></span> XOF</p>
                      </div>
                    </div>
                    <div class="row">
                      <div class="block-info">
                        <p class="total-price">soit<span class="total-price px-1" data-price="<%= flat.price_per_day %>" data-flat="<%= flat.id %>"></span>€</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
          </div>
          <%= link_to new_contact_path, class: "link-to-contact" do  %>
            <div class="cars-info ml-4">
              <div class="car-info m-4 bg-white">
                  <div class="photo-car d-flex align-items-center justify-content-center">
                    <%= image_tag "kia-sportage-.jpg", class: "photo-car-index", crop: :scale %>
                  </div>
                  <div class="block-infos">
                    <div class="block-info mt-2">
                      <h3 class="pt-2" id="flat-name-index">Vous souhaitez louer une voiture ?</h3>
                      <p class="car-text">Avec ou sans chauffeur ? Pour l'aéroport ou toute la durée de votre séjour ?</p>
                      <p class="car-text">Retrouvez tous les renseignements lors de votre réservation d'appartement.</p>
                    </div>
                  </div>
              </div>
            </div>
          <% end %>
        </div>

          <div class="col-md-4">
            <div
              id="map"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
            ></div>
          </div>
      </div>
    <% else %>

    <div class="d-flex align-items-center justify-content-center pt-5 mt-5">
      <h1 class="title-index-flat">Nous n'avons pas d'appartements disponibles selon vos critères de recheche</h1>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container bg-white my-5 new-flat">
  <h1 class="p-4">Créer une annonce</h1>
    <%= simple_form_for @flat do |f| %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <%= f.input :name,
                    as: :string,
                    required: true,
                    label: 'Nom' %>
        <%= f.input :price_per_day,
                    as: :integer,
                    required: true,
                    label: 'Prix par nuit en euro' %>
        <%= f.input :price_xof,
                    as: :integer,
                    required: true,
                    label: 'Prix par nuit en XOF' %>
        <%= f.input :description,
                    as: :text,
                    required: true,
                    label: 'Description' %>
        <%= f.input :offer,
                    as: :text,
                    required: false,
                    label: 'Offre' %>
        <%= f.input :longitude,
                    as: :hidden %>
        <%= f.input :latitude,
                    as: :hidden %>
        <div class="row">
          <div class="col">
        <%= f.input :min_capacity,
                    as: :integer,
                    required: true,
                    label: "Nombre de personnes minimum"%>
           </div>
           <div class="col">
        <%= f.input :max_capacity,
                    as: :integer,
                    required: true,
                    label: "Nombre de personnes maximum"%>
          </div>
        </div>
        <%= f.input :picture,
                    as: :file,
                    required: true,
                    label: 'Photo principale' %>
        <%= f.input :photos,
                    as: :file,
                    input_html: { multiple: true },
                    label: 'Photos secondaires' %>
        <%= f.collection_radio_buttons :belonging,
                    [[true, 'Immeuble Comara'],
                    [false, 'Partenaire']],
                    :first, :last,
                    label: "Appartenance" %>
        <div class="geolocation d-none">
          <div class="row">
            <div class="col">
              <%= f.input :longitude,
                          as: :float,
                          label: "Longitude" %>
            </div>
            <div class="col">
              <%= f.input :latitude,
                          as: :float,
                          label: "Latitude" %>
            </div>
          </div>
        </div>
          <div class="row">
          <%= f.simple_fields_for :equipment do |c| %>
            <div class="col-md-6">
              <div class="row">
                <div class="equipment-new w-100 m-3">
                  <div class="col-md-4">
                    <p class="equipment-name w-100"><%= t(c.object.name) %></p>
                  </div>
                  <%= c.input :name, as: :hidden %>
                  <%= c.input :icon, as: :hidden %>
                  <div class="col-md-3">
                    <%= c.input :available, as: :boolean, label: 'Disponible' %>
                  </div>
                  <div class="col-md-5">
                    <%= c.input :pricing, as: :boolean, label: 'Disponible (payant)' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          </div>
          <div class="d-flex justify-content-center">
            <%= f.submit "Créer", class: 'back-to-home-link my-5' %>
          </div>
        </div>
    <% end %>
</div>

app/views/flats/show.html.erb
<div id="show-flat">
  <div class="container px-0 w-100">
    <div class="display-photos w-100">
      <div class="display-photos-container d-none">
        <%= render 'photos' %>
      </div>
    </div>
    <div class="contenu-show mt-3 pt-2">
      <h1 class="title-index-flat mt-5"><%= @flat.name %></h1>
      <div class="photo-show-flat" id="photo-show-flat">
        <div class="photos-show-flat">
          <div class="col d-flex py-4">
            <%= cl_image_tag @flat.picture.key, crop: :fit, class: "photo-flat-index-principale" %>
          </div>
          <div class="col">
            <div class="row pt-3 pb-2">
              <% @flat.photos.each do |photo| %>
                <div class=" p-2">
                  <%= cl_image_tag photo.key, crop: :fill_pad, class: "photo-flat-index-secondaire" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="description-booking mb-5">
        <div class="row">
          <div class="col-md-8 mt-4 p-0">
            <div class="description-show-flat p-2">
              <div class="description-flat-show">
                <h3 class="titles-description-flat pt-4 pb-2 mx-3">Description de l'appartement</h3>
                <div class="text-description-flat mx-3">
                  <p><%= @flat.description %></p>
                  <p class="offer-text"><%= @flat.offer %></p>
                </div>
              </div>
              <div class="equipement-flat-show p-2">
                <h3 class="titles-description-flat pb-2 mx-3">Équipements de l'appartement</h3>
                  <div class="list-equipements px-3">
                    <div class="row">
                      <div class="col">
                        <div class="row">
                          <% @flat.equipment.each do |equipment| %>
                            <% if equipment.available == true %>
                              <div class="col-md-6 d-flex">
                                <i class="<%= equipment.icon %>"></i>
                                <p class="ml-2"><%= t(equipment.name) %></p>
                              </div>
                             <% elsif equipment.pricing == true %>
                              <div class="col-md-6 d-flex">
                                <i class="<%= equipment.icon %>"></i>
                                <p class="ml-2"><%= t(equipment.name) %> (payant)</p>
                              </div>
                            <% end %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="accessibility-hours">
                <h3 class="titles-description-flat pb-2 mx-3">Accessibilité et horaire</h3>
                <div class="text-hours-accessibility d-flex m-3">
                  <i class="fal fa-clock px-2"></i>
                  <p>Heure d'arrivée : à partir de 15:00</p>
                  <i class="fas fa-clock px-2"></i>
                  <p>Heure de départ : 11:00</p>
                </div>
                <div class="justify-content-center d-flex align-items-center">
                  <a class="button-booking" target="_blank" href="https://www.google.fr/maps/place/6CQR822J%2BVR/@5.301085,-3.9713232,15z/data=!4m5!3m4!1s0x0:0x0!8m2!3d5.3021875!4d-3.9679375">Nous trouver</a>
                </div>
              </div>

            </div>
          </div>
          <div class="col-md-4 mt-4">
            <div class="booking-show-flat">
              <div class="d-flex d-print-inline justify-content-center pt-4">
                <p id="price-per-day" data-price="<%= @flat.price_per_day %>"><%= @flat.price_xof.to_s.split("").reverse.each_slice(3).map {|y| y.join("").reverse}.reverse.join(" ") %> XOF/<span id="price-day-word">nuit</span></p>
                <p id="price-per-day-xof" data-price="<%= @flat.price_xof %>"></p>
              </div>
               <%= render 'bookings/form', flat: @flat, booking: @booking %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>