config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  get 'pages/rules'
  get 'pages/rgpd'
  get 'pages/presentation'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :user do
    resources :bookings, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :accepted
        patch :refused
      end
    end
    resources :flats, only: [:index] do
    end
  end

  resources :flats do
    resources :bookings, only: [:new, :create]
    member do
      patch :delete_photos
    end
  end

  resources :client, only: [:new, :create] do
    resources :bookings, only: [:create]
  end

 resources :bookings, only: [:new, :create, :show, :edit, :update]

 resources :contacts, only: [:new, :create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer py-5 text-center">
  <div class="footer-category w-100">
    <div class="col px-0">
      <%= link_to pages_rgpd_path, class: "link-footer" do %>
        <p>Politique de confidentialité</p>
      <% end %>
    </div>
    <div class="col px-0">
      <%= link_to pages_rules_path, class: "link-footer" do %>
        <p>Réglèment intérieur</p>
      <% end %>
    </div>
    <div class="col px-0">
      <%= link_to pages_presentation_path, class: "link-footer" do %>
        <p>Qui sommes-nous ?</p>
      <% end %>
    </div>
    <div class="col px-0">
      <%= link_to  pages_contact_path, class: "link-footer" do %>
        <p>Nous contacter</p>
      <% end %>
    </div>
    <div class="col">
      <%= link_to  "https://www.facebook.com/Immeuble-Comara-locations-de-vacances-Abidjan-104556534617035/", class: "link-footer" do %>
        <i class="fab fa-facebook-square"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon m-0">
  <%= link_to "/", class: "navbar-brand" do %>
    <h1 class="pl-4">Immeuble Comara</h1>
    <% end %>

      <% if user_signed_in? %>
        <div class="row w-100">
          <div class="col text-center">
          <%= link_to "Appartements", user_flats_path, class: "navbar-menu" %>
          </div>
          <div class="col text-center">
          <%= link_to "Réservations", user_bookings_path, class: "navbar-menu" %>
          </div>
          <div class="col text-center">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "navbar-menu" %>
          </div>
        </div>
      <% end %>

  </div>
</div>