config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  get 'pages/rules'
  get 'pages/rgpd'
  get 'pages/presentation'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :user do
    resources :bookings, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        patch :accepted
        patch :refused
      end
    end
    resources :flats, only: [:index] do
    end
  end

  resources :flats do
    resources :bookings, only: [:new, :create]
    member do
      patch :delete_photos
    end
  end

  resources :client, only: [:new, :create] do
    resources :bookings, only: [:create]
  end

 resources :bookings, only: [:new, :create, :show, :edit, :update]

 resources :contacts, only: [:new, :create]
end

app/models/booking.rb
class Booking < ApplicationRecord
  TRAVELLERS = [1, 2, 3, 4, 5, 6]
  STATUS = ["pending", "refused", "confirmed"]

  belongs_to :flat
  belongs_to :client

  accepts_nested_attributes_for :client

  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, through: :flats
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :new, :create]
  before_action :set_flat, only: [:new, :create]
  before_action :set_booking, only: [:show, :edit, :update]

  def show
  end

  def new
    @client = Client.new
    @booking = @client.build_booking(booking_params)
    @booking.total_price = @flat.price_per_day*((@booking.end_date - @booking.start_date).to_i)
    @booking.total_price_xof = @flat.price_xof*((@booking.end_date - @booking.start_date).to_i)
  end

  def create
    @client = Client.new(client_params)
    @booking = @client.booking
    @booking.flat = @flat
    @booking.total_price = @booking.flat.price_per_day*((@booking.end_date - @booking.start_date).to_i)
    @booking.total_price_xof = @booking.flat.price_xof*((@booking.end_date - @booking.start_date).to_i)
    @booking.status = 'pending'
    @booking.origin = 'Site internet'
    if @booking.airport_car = true
      @booking.total_price_xof + 30000
    end
    if @client.save
      mail = UserMailer.with(booking: @booking).welcome.deliver_now
      mail_notif = UserMailer.new_booking.deliver_now
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @display_flat_names = Flat.order(:name).map do | flat |
      [flat.name, flat.id]
    end
  end

  def update
    @booking.update(booking_params)

    if @booking.save
      redirect_to user_bookings_path
    else
      render :edit
    end
  end

private

  def booking_params
    params.require(:booking).permit(
    :start_date,
    :end_date,
    :travellers,
    :flat_id,
    :total_price,
    :total_price_xof,
    :status,
    :origin,
    :airport_car,
    :airport_car_back,
    :rental_car,
    client_attributes: [:id, :civilty, :first_name, :last_name, :address, :phone_number, :email])
  end

  def client_params
    params.require(:client).permit(
      :civilty,
      :first_name,
      :last_name,
      :address,
      :phone_number,
      :email,
      booking_attributes: [:start_date, :end_date, :travellers])
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/user/bookings_controller.rb
class User::BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy refused_booking accepted_booking]

  def index
    @bookings = Booking.all
    @bookings_accepted = Booking.where(status: 'confirmed')
    @clients = Client.all
  end
  def new
    @booking = Booking.new
      @display_flat_names = Flat.order(:name).map do | flat |
        [flat.name, flat.id]
      end
    @client = @booking.build_client

  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to user_bookings_path
    else
      render :new
    end
  end

  def edit
  end
  def update
    @booking.update(booking_params)

    if @booking.save
      redirect_to user_bookings_path
    else
      render :edit
    end
  end
  def destroy
    @booking.destroy
    redirect_to user_bookings_path
  end

  def refused
    @booking = Booking.find(params[:id])
    @booking.update(status: 'refused')
    flash[:refused] = "La réservation est refusée."
    redirect_to user_bookings_path
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.update(status: 'confirmed')
    flash[:confirmed] = "La réservation est confirmée."
    redirect_to user_bookings_path
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(
      :id,
      :start_date,
      :end_date,
      :travellers,
      :flat_id,
      :total_price,
      :total_price_xof,
      :status,
      :origin,
      :airport_car,
      :airport_car_back,
      :rental_car,
      client_attributes: [:id, :civilty, :first_name, :last_name, :address, :phone_number, :email])
  end


  # def set_flat
  #   @flat = Flat.all
  # end
end

app/controllers/user/flats_controller.rb
class User::FlatsController < ApplicationController
  def index
    @flats_comara = Flat.where(belonging: true)
    @flats_partners = Flat.where(belonging: false)
  end
end

app/views/user/bookings/edit.html.erb
<p>blabla</p>

app/views/user/bookings/index.html.erb
<div class="container-fluid">
    <div class="message-flash"><%= flash[:confirmed] %></div>
    <div class="message-flash"><%= flash[:refused] %></div>
  <div class="booking-waiting">
    <h1>Demandes en attente</h1>
    <% @bookings.each do |booking| %>
      <% if booking.status == 'pending' %>
        <div class="row">
          <div class="col">
            <div class="card-user-booking-wait bg-white p-2 my-2">
              <div class="row">
                <div class="col">
                  <p class="flat-name-booking"><%= booking.flat.name %> </p>
                  <p><%= l(booking.start_date, format: '%d %B') %> - <%= l(booking.end_date, format: '%d %B %Y') %></p>
                  <p><%= booking.total_price %>€</p>
                  <div class="d-flex">
                    <% if booking.airport_car = true %>
                      <p class="pr-2">Navette allé</p>
                    <% end %>
                    <% if booking.airport_car_back = true %>
                      <p class="pr-2">Navette retour</p>
                    <% end %>
                  </div>
                    <% if booking.rental_car = true %>
                      <p class="pr-2">Location de voiture</p>
                    <% end %>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                  <div class="mx-2">
                    <%= link_to accepted_user_booking_path(booking), method: :patch do %>
                      <i class="fas fa-check-circle" id="check-circle"></i>
                    <% end %>
                  </div>
                  <div class="mx-2">
                    <%= link_to refused_user_booking_path(booking), method: :patch do %>
                      <i class="fas fa-times-circle" id="no-circle"></i>
                    <% end %>
                  </div>
                  <div class="mx-2">
                    <i class="fas fa-user-circle" id="user-circle" data="<%= booking.id %>"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-booking-client bg-white my-2 p-2 d-none" data="<%= booking.id %>">
              <p class="flat-name-booking"><%= booking.client.first_name %> <%= booking.client.last_name %></p>
              <p><%= booking.client.phone_number %></p>
              <p><%= booking.client.address %></p>
              <p><%= booking.client.email %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="calendar bg-white m-4">
    <div class="calendar-view pt-3">
      <div class="row my-3">
        <h1 class="ml-4">Calendrier</h1>
        <%= link_to new_user_booking_path, class: "link-to-new-booking" do  %>
          <h1 class="add-booking mx-3">+</h1>
        <% end %>
      </div>
      <%= month_calendar do |date| %>
      <div class="text-right">
        <p class="calday text-center"  data-date="<%= l(date, format: '%Y-%m-%d') %>"><%= l(date, format: '%d', class: "date-calendar") %></p>
      </div>
      <% end %>
    </div>
    <div class="calendar-text">
      <div class="row">
        <div class="col m-4">
          <div class="calendar-content-text d-flex justify-content-center w-100">
            <h3>Arrivée</h3>
          </div>
          <div class="date-booking-action">
            <% @bookings_accepted.each do |booking| %>
              <div class="card-user-booking p-3" data-date="<%= booking.start_date %>" data-booking="<%= booking.client_id %>">
                <p class="flat-name-booking"><%= booking.flat.name %></p>
                <div class="d-flex">
                  <p class="start-date-booking"><%= l(booking.start_date, format: '%d %B %Y') %></p>
                  <p class="mx-2">-</p>
                  <p class="end-date-booking"><%= l(booking.end_date, format: '%d %B %Y') %></p>
                </div>
                <% if booking.airport_car = true %>
                  <p>Navette aéroport allé</p>
                <% end %>
                <%= link_to 'Modifier', edit_booking_path(booking), class: 'link-flat'  %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col m-4">
          <div class="calendar-content-text d-flex justify-content-center w-100">
            <h3>En cours</h3>
          </div>
          <div class="date-booking-action">
            <% @bookings_accepted.each do |booking| %>
              <div class="card-user-booking p-3" data-date="<%= (booking.start_date+1..booking.end_date-1).to_a.map{|date| l(date, format: '%Y-%m-%d')} %>" data-booking="<%= booking.client_id %>">
                <p class="flat-name-booking"><%= booking.flat.name %></p>
                <div class="d-flex">
                  <p class="start-date-booking"><%= l(booking.start_date, format: '%d %B %Y') %></p>
                  <p class="mx-2">-</p>
                  <p class="end-date-booking"><%= l(booking.end_date, format: '%d %B %Y') %></p>
                </div>
                <%= link_to 'Modifier', edit_booking_path(booking), class: 'link-flat'  %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col m-4">
          <div class="calendar-content-text">
            <div class="title-calendar-text d-flex justify-content-center w-100">
            <h3>Départ</h3>
            </div>
            <div class="date-booking-action">
              <% @bookings_accepted.each do |booking| %>
                <div class="card-user-booking p-3" data-date="<%= booking.end_date %>" data-booking="<%= booking.client_id %>">
                  <p class="flat-name-booking"><%= booking.flat.name %></p>
                  <div class="d-flex">
                    <p class="start-date-booking"><%= l(booking.start_date, format: '%d %B %Y') %></p>
                    <p class="mx-2">-</p>
                    <p class="end-date-booking"><%= l(booking.end_date, format: '%d %B %Y') %></p>
                  </div>
                  <% if booking.airport_car_back = true %>
                    <p>Navette aéroport retour</p>
                  <% end %>
                  <%= link_to 'Modifier', edit_booking_path(booking), booking: @booking, class: 'link-flat'  %>
                </div>
              <% end %>
            </div>
           </div>
          </div>
        </div>
      </div>
      <div class="client-info-display justify-content-center d-flex align-items-center">
        <div class="card-client-booking text-center">
          <% @clients.each do |client| %>
            <div class="client-info p-2" data-booking="<%= client.id %>">
              <p><i class="fal fa-user px-2"></i><%= client.first_name %> <%= client.last_name %></p>
              <p><i class="fal fa-envelope px-2"></i><%= client.email %></p>
              <p><i class="fal fa-phone px-2"></i><%= client.phone_number %></p>
              <p><i class="fal fa-house px-2"></i><%= client.address %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/bookings/new.html.erb
<div class="container bg-white p-5 my-5 user-new-booking">
  <h1>Nouvelle réservation</h1>
   <%= simple_form_for @booking, url: user_bookings_path do |f| %>
      <% if @booking.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @booking.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.association :flat,
            required: false,
            input_html: {class: "select2"},
            label: 'Appartement',
            collection: @display_flat_names %>
      <div class="row">
        <div class="col">
          <%= f.input :total_price_xof,
                      as: :integer,
                      required: true,
                      label: 'Prix total XOF' %>
        </div>
        <div class="col">
          <%= f.input :total_price,
                as: :integer,
                required: true,
                label: 'Prix Total en Euro' %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.input :start_date,
            as: :string,
            required: true,
            input_html: {id: "range_start"},
            label: 'Dates d\'arrivée' %>
        </div>
        <div class="col">
          <%= f.input :end_date,
            as: :string,
            required: true,
            input_html: {id: "range_end"},
            label: 'Date de départ' %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.input :travellers,
              as: :select,
              collection: Booking::TRAVELLERS,
              input_html: {class: "select2"},
              label: 'Nombre de Voyageurs' %>
        </div>
        <div class="col">
          <%= f.input :status,
              as: :select,
              collection: Booking::STATUS,
              input_html: {class: "select2"},
              required: true,
              label: 'Statut de la réservation' %>
        </div>
        <div class="col">
          <%= f.input :origin,
                as: :string,
                required: true,
                label: "Origine de réservation" %>
        </div>
      </div>
      <%= f.input :airport_car, as: :boolean, label: "Navette allée." %>
      <%= f.input :airport_car_back, as: :boolean, label: "Navette retour." %>
      <%= f.input :rental_car, as: :boolean, label: "Demande de devis location voiture." %>
      <div class="pt-5">
        <div class="d-flex">
          <h3 class="mr-3">Coordonées du client</h3>
          <%= render "bookings/emails/nouvelle_reservation" %>
        </div>
        <%= f.simple_fields_for :client do |c| %>
          <div class="row">
            <div class="col">
              <%= c.input :civility, as: :select, collection: Client::CIVILITY, required: true, label: "Civilité" %>
            </div>
            <div class="col">
              <%= c.input :first_name, as: :string, required: true, label: "Prénom" %>
            </div>
            <div class="col">
              <%= c.input :last_name, as: :string, required: true, label: "Nom de Famille" %>
            </div>
          </div>
          <%= c.input :address, as: :string, required: true, label: "Adresse postale" %>
          <div class="row">
            <div class="col">
              <%= c.input :phone_number, as: :string, required: true, label: "Numéro de téléphone"  %>
            </div>
            <div class="col">
              <%= c.input :email, as: :string, required: true, label: "Adresse e-mail" %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="d-flex justify-content-center">
        <%= f.submit "Créer", class: 'back-to-home-link my-5' %>
      </div>
    </div>
  <% end %>
</div>